"""
Secure Read-Only Web Viewer for Mobile Forensics Investigation Tool

FORENSIC ROLE:
- Provides secure, read-only web interface for forensic evidence viewing
- Displays investigation results without allowing evidence modification
- Ensures chain of custody integrity (no POST operations)
- Presents timeline, analysis findings, and reports in web format

SECURITY CONSTRAINTS:
- READ-ONLY interface (no POST, PUT, DELETE operations)
- No evidence modification capabilities
- No file upload or download features
- Session-based viewing only
- All data displayed is pre-processed and static

INTEGRATION NOTES:
- This UI only DISPLAYS pre-generated JSON files
- INTEGRATOR RESPONSIBILITY: Run extraction/analysis scripts first
- Gracefully handles missing files with clear status messages
- Never crashes - always shows meaningful status
- File paths are relative to ui/ directory

ROUTES:
- / : Main dashboard with investigation overview
- /dashboard : Investigation summary and statistics
- /evidence : Evidence integrity and hash verification
- /timeline : Unified timeline viewer
- /report : Complete forensic report viewer

EXPECTED FILE STRUCTURE (for integration):
../timeline/timeline.json                    # Generated by timeline/timeline_builder.py
../analysis/findings.json                    # Merged findings from all analysis scripts
../evidence/hashes/hashes.json               # Generated by analysis/hash_generator.py
../reports/forensic_report.json             # Generated by reports/generate_report.py (preview)
"""

from flask import Flask, render_template_string, jsonify, request, redirect, url_for, session
import json
import os
from datetime import datetime

app = Flask(__name__)
app.secret_key = 'forensic-session-key'  # Required for session management

# Multi-case forensic investigation setup
def discover_cases():
    """
    Discover all valid cases in the cases/ directory.
    
    A valid case must contain:
    - metadata.json
    - evidence/
    - analysis/findings.json
    - timeline/timeline.json
    - reports/forensic_report.pdf
    
    Returns:
        list: List of valid case dictionaries
    """
    cases_dir = "../cases"
    valid_cases = []
    
    if not os.path.exists(cases_dir):
        print(f"Cases directory not found: {cases_dir}")
        return valid_cases
    
    for case_id in os.listdir(cases_dir):
        case_path = os.path.join(cases_dir, case_id)
        
        # Skip non-directories
        if not os.path.isdir(case_path):
            continue
        
        # Validate case structure
        required_files = [
            os.path.join(case_path, "metadata.json"),
            os.path.join(case_path, "evidence"),
            os.path.join(case_path, "analysis", "findings.json"),
            os.path.join(case_path, "timeline", "timeline.json"),
            os.path.join(case_path, "reports", "forensic_report.pdf")
        ]
        
        if all(os.path.exists(path) for path in required_files):
            # Load case metadata
            try:
                metadata_path = os.path.join(case_path, "metadata.json")
                with open(metadata_path, 'r') as f:
                    metadata = json.load(f)
                
                case_info = {
                    "case_id": case_id,
                    "device_model": metadata.get("device_type", "Unknown"),
                    "dataset_source": metadata.get("data_source", "Unknown"),
                    "case_name": metadata.get("case_name", case_id),
                    "investigator": metadata.get("investigator", "Unknown")
                }
                valid_cases.append(case_info)
                print(f"Discovered valid case: {case_id}")
                
            except Exception as e:
                print(f"Error loading metadata for case {case_id}: {e}")
        else:
            print(f"Case {case_id} missing required files, skipping")
    
    return valid_cases

# Global case discovery
AVAILABLE_CASES = discover_cases()
DEFAULT_CASE = AVAILABLE_CASES[0]["case_id"] if AVAILABLE_CASES else "case_001"

# Session-based active case management
def get_active_case():
    """Get the currently active case from session or default"""
    return session.get('active_case', DEFAULT_CASE)

def set_active_case(case_id):
    """Set the active case in session"""
    session['active_case'] = case_id

def get_case_base_path():
    """Get the base path for the active case"""
    active_case = get_active_case()
    return f"../cases/{active_case}"

# HTML templates for each route
DASHBOARD_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        .header { text-align: center; color: #333; border-bottom: 2px solid #007bff; padding-bottom: 20px; }
        .nav { margin: 20px 0; text-align: center; }
        .nav a { margin: 0 15px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .nav a:hover { background: #0056b3; }
        .status { background: #d4edda; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .integration-status { background: #fff3cd; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .progress-bar { width: 100%; height: 20px; background: #e9ecef; border-radius: 10px; overflow: hidden; margin: 10px 0; }
        .progress-fill { height: 100%; background: #28a745; transition: width 0.3s ease; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Secure Read-Only Evidence Viewer</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        <div class="status">
            <h3>Dashboard Status</h3>
            <p><strong>Investigation Status:</strong> {{ "Active Analysis" if integration_status.completion_percentage < 100 else "Complete" }}</p>
            <p><strong>Evidence Integrity:</strong> {{ "Verified" if hash_verified else "Pending" }}</p>
            <p><strong>Timeline Events:</strong> {{ timeline_events }}</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        
        <div class="integration-status">
            <h3>Integration Progress</h3>
            <p><strong>Overall Status:</strong> {{ integration_status.overall_status }}</p>
            <div class="progress-bar">
                <div class="progress-fill" style="width: {{ integration_status.completion_percentage }}%"></div>
            </div>
            <p><strong>Completion:</strong> {{ "%.1f"|format(integration_status.completion_percentage) }}%</p>
            
            <h4>Component Status:</h4>
            <ul>
                <li>Timeline: {{ "✅ Ready" if integration_status.timeline else "❌ Not Generated" }}</li>
                <li>Analysis Findings: {{ "✅ Complete" if integration_status.findings else "❌ Pending" }}</li>
                <li>Hash Verification: {{ "✅ Complete" if integration_status.hashes else "❌ Pending" }}</li>
                <li>Forensic Report: {{ "✅ Ready" if integration_status.forensic_report else "❌ Not Generated" }}</li>
            </ul>
        </div>
        
        <div class="status">
            <h3>Case Selection</h3>
            <form method="POST" action="/select_case" style="margin-bottom: 20px;">
                <label for="case_select"><strong>Select Active Case:</strong></label><br/>
                <select id="case_select" name="case_id" onchange="this.form.submit()" style="margin-top: 5px; padding: 5px; width: 300px;">
                    {% for case in available_cases %}
                    <option value="{{ case.case_id }}" {% if case.case_id == active_case %}selected{% endif %}>
                        {{ case.case_id }} - {{ case.case_name }}
                    </option>
                    {% endfor %}
                </select>
            </form>
        </div>
        
        <div class="status">
            <h3>Case Overview</h3>
            <p><strong>Active Case:</strong> {{ case_metadata.case_id }}</p>
            <p><strong>Case Name:</strong> {{ case_metadata.case_name }}</p>
            <p><strong>Investigator:</strong> {{ case_metadata.investigator }}</p>
            <p><strong>Device Type:</strong> {{ case_metadata.device_type }}</p>
            <p><strong>Data Source:</strong> {{ case_metadata.data_source }}</p>
            <p><strong>Case Status:</strong> {{ case_metadata.case_status }}</p>
            <p><strong>Suspicion Level:</strong> 
                <span style="padding: 2px 8px; border-radius: 3px; color: white; font-weight: bold;
                    {% if case_suspicion.suspicion_level == 'Clean' %}background: #28a745;
                    {% elif case_suspicion.suspicion_level == 'Suspicious' %}background: #ffc107; color: #000;
                    {% else %}background: #dc3545;{% endif %}">
                    {{ case_suspicion.suspicion_level }} (Score: {{ case_suspicion.score }})
                </span>
            </p>
            {% if case_suspicion.reasons %}
            <p><strong>Classification Reasons:</strong></p>
            <ul style="margin: 5px 0; padding-left: 20px;">
                {% for reason in case_suspicion.reasons %}
                <li>{{ reason }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <p style="margin-top: 15px; padding: 10px; background: #e7f3ff; border-left: 4px solid #007bff;">
                <strong>Note:</strong> All evidence, timeline, and reports shown belong to the active case.
            </p>
        </div>
        
        <h3>Investigation Overview</h3>
        <p>This secure interface provides read-only access to forensic evidence and analysis results.</p>
        <p><strong>INTEGRATOR NOTE:</strong> Run the extraction and analysis scripts to populate this dashboard.</p>
    </div>
</body>
</html>
"""

EVIDENCE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Evidence</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        .header { text-align: center; color: #333; border-bottom: 2px solid #28a745; padding-bottom: 20px; }
        .nav { margin: 20px 0; text-align: center; }
        .nav a { margin: 0 15px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .nav a:hover { background: #0056b3; }
        .evidence-status { background: #fff3cd; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-missing { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-ready { background: #d4edda; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-error { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Evidence Integrity & Hash Verification</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if hash_status == "missing" %}
        <div class="status-missing">
            <h3>⚠️ Evidence Integrity Status</h3>
            <p><strong>Chain of Custody:</strong> Not Established</p>
            <p><strong>Hash Verification:</strong> {{ hash_message }}</p>
            <p><strong>Evidence Source:</strong> NIST CFReDS Android Dataset</p>
            <p><strong>INTEGRATOR ACTION:</strong> Run <code>analysis/hash_generator.py</code> to generate hash manifest</p>
        </div>
        {% elif hash_status == "error" %}
        <div class="status-error">
            <h3>❌ Evidence Integrity Error</h3>
            <p><strong>Chain of Custody:</strong> Error</p>
            <p><strong>Hash Verification:</strong> {{ hash_message }}</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        {% else %}
        <div class="status-ready">
            <h3>✅ Evidence Integrity Status</h3>
            <p><strong>Chain of Custody:</strong> Maintained</p>
            <p><strong>Hash Verification:</strong> SHA-256 Verified</p>
            <p><strong>Total Files Hashed:</strong> {{ total_files }}</p>
            <p><strong>Integrity Score:</strong> {{ "%.1f"|format(integrity_score) }}%</p>
            <p><strong>Evidence Source:</strong> NIST CFReDS Android Dataset</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        {% endif %}
        
        <h3>Evidence Overview</h3>
        <p>All evidence files are cryptographically verified using SHA-256 hashes to ensure forensic integrity.</p>
        <p><strong>FORENSIC NOTE:</strong> Hash verification ensures evidence has not been tampered with since acquisition.</p>
        
        {% if hash_status == "missing" %}
        <div class="status-missing">
            <h4>Next Steps:</h4>
            <ol>
                <li>Place raw evidence files in <code>evidence/raw/</code></li>
                <li>Run <code>cd analysis && python hash_generator.py</code></li>
                <li>Refresh this page to verify integrity</li>
            </ol>
        </div>
        {% endif %}
    </div>
</body>
</html>
"""

TIMELINE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Timeline</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        .header { text-align: center; color: #333; border-bottom: 2px solid #17a2b8; padding-bottom: 20px; }
        .nav { margin: 20px 0; text-align: center; }
        .nav a { margin: 0 15px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .nav a:hover { background: #0056b3; }
        .timeline-info { background: #d1ecf1; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-missing { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-ready { background: #d4edda; padding: 15px; border-radius: 4px; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Unified Event Timeline</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if timeline_status == "missing" %}
        <div class="status-missing">
            <h3>⚠️ Timeline Not Generated</h3>
            <p><strong>Status:</strong> Timeline not generated yet</p>
            <p><strong>Total Events:</strong> 0</p>
            <p><strong>Date Range:</strong> Not available</p>
            <p><strong>INTEGRATOR ACTION:</strong> Run <code>timeline/timeline_builder.py</code> to generate timeline</p>
        </div>
        {% else %}
        <div class="status-ready">
            <h3>✅ Timeline Information</h3>
            <p><strong>Total Events:</strong> {{ total_events }}</p>
            <p><strong>Date Range:</strong> {{ date_range_start }} to {{ date_range_end }}</p>
            <p><strong>Sources:</strong> {{ sources|join(', ') if sources else 'None' }}</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        {% endif %}
        
        <h3>Event Timeline</h3>
        <p>Timeline displays all events from SMS, calls, media, and app usage in chronological order.</p>
        
        {% if timeline_status == "missing" %}
        <div class="status-missing">
            <h4>Next Steps:</h4>
            <ol>
                <li>Run extraction scripts: <code>cd extractor && python extract_*.py</code></li>
                <li>Run analysis scripts: <code>cd analysis && python *_analysis.py</code></li>
                <li>Generate timeline: <code>cd timeline && python timeline_builder.py</code></li>
                <li>Refresh this page to view timeline</li>
            </ol>
        </div>
        {% else %}
        <div class="timeline-info">
            <h4>Timeline Statistics:</h4>
            <ul>
                <li>Total chronological events: {{ total_events }}</li>
                <li>Time span: {{ date_range_start }} to {{ date_range_end }}</li>
                <li>Data sources: {{ sources|length if sources else 0 }} different sources</li>
            </ul>
            <p><strong>FORENSIC NOTE:</strong> Timeline reconstruction provides chronological context for investigation.</p>
        </div>
        {% endif %}
    </div>
</body>
</html>
"""

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        .header { text-align: center; color: #333; border-bottom: 2px solid #dc3545; padding-bottom: 20px; }
        .nav { margin: 20px 0; text-align: center; }
        .nav a { margin: 0 15px; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
        .nav a:hover { background: #0056b3; }
        .report-status { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-missing { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-ready { background: #d4edda; padding: 15px; border-radius: 4px; margin: 20px 0; }
        .status-error { background: #f8d7da; padding: 15px; border-radius: 4px; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Complete Forensic Report</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if report_status == "missing" %}
        <div class="status-missing">
            <h3>⚠️ Report Not Generated</h3>
            <p><strong>Report Generation:</strong> {{ report_message }}</p>
            <p><strong>Analysis Complete:</strong> Pending</p>
            <p><strong>Court Ready:</strong> Not Available</p>
            <p><strong>INTEGRATOR ACTION:</strong> Run <code>reports/generate_report.py</code> to generate forensic report</p>
        </div>
        {% elif report_status == "error" %}
        <div class="status-error">
            <h3>❌ Report Generation Error</h3>
            <p><strong>Report Generation:</strong> Error</p>
            <p><strong>Error Message:</strong> {{ report_message }}</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        {% else %}
        <div class="status-ready">
            <h3>✅ Report Status</h3>
            <p><strong>Report Generation:</strong> Complete</p>
            <p><strong>Analysis Complete:</strong> Yes</p>
            <p><strong>Risk Level:</strong> {{ risk_level }}</p>
            <p><strong>Total Events Analyzed:</strong> {{ total_events }}</p>
            <p><strong>Report Generated:</strong> {{ report_timestamp }}</p>
            <p><strong>Court Ready:</strong> Final Review Required</p>
            <p><strong>Last Updated:</strong> {{ timestamp }}</p>
        </div>
        {% endif %}
        
        <h3>Forensic Investigation Report</h3>
        <p>Comprehensive report includes timeline analysis, behavioural findings, malware detection, and evidence integrity verification.</p>
        
        {% if report_status == "missing" %}
        <div class="status-missing">
            <h4>Next Steps:</h4>
            <ol>
                <li>Complete all analysis scripts: <code>cd analysis && python *_analysis.py</code></li>
                <li>Generate timeline: <code>cd timeline && python timeline_builder.py</code></li>
                <li>Generate report: <code>cd reports && python generate_report.py</code></li>
                <li>Refresh this page to view report</li>
            </ol>
        </div>
        {% else %}
        <div class="status-ready">
            <h4>Report Contents:</h4>
            <ul>
                <li>Evidence integrity verification with SHA-256 hashes</li>
                <li>Timeline reconstruction with chronological events</li>
                <li>Behavioural analysis with suspicious pattern detection</li>
                <li>Malware analysis with indicator identification</li>
                <li>Anomaly analysis with temporal inconsistency detection</li>
                <li>Executive summary with risk assessment</li>
            </ul>
            <p><strong>FORENSIC NOTE:</strong> This report is court-ready and maintains chain of custody integrity.</p>
            
            <div style="margin-top: 20px;">
                <a href="/download/report" download="forensic_report.pdf" style="background: #28a745; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;">
                    � Download Forensic Report (PDF)
                </a>
            </div>
        </div>
        {% endif %}
    </div>
</body>
</html>
"""

@app.route('/')
def dashboard():
    """Main dashboard route - investigation overview with integration status"""
    # Get integration status
    integration_status = get_integration_status()
    
    # Load case metadata
    case_metadata = load_case_metadata()
    
    # Get active case and available cases
    active_case = get_active_case()
    available_cases = AVAILABLE_CASES
    
    # Load case suspicion classification
    case_suspicion = load_case_suspicion(active_case)
    
    # Load available data gracefully
    timeline_data = load_timeline_data()
    analysis_data = load_analysis_data()
    hash_data = load_hash_data()
    report_data = load_report_data()
    
    # Prepare dashboard context
    context = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "integration_status": integration_status,
        "case_metadata": case_metadata,
        "active_case": active_case,
        "available_cases": available_cases,
        "case_suspicion": case_suspicion,
        "timeline_events": len(timeline_data),
        "analysis_complete": all(
            isinstance(analysis_data.get(key, []), list) and len(analysis_data.get(key, [])) > 0
            for key in ["suspicious_behaviour", "malware_indicators", "timestamp_anomalies"]
        ),
        "hash_verified": hash_data.get("status") != "missing",
        "report_ready": report_data.get("status") != "missing"
    }
    
    return render_template_string(DASHBOARD_TEMPLATE, **context)

@app.route('/select_case', methods=['POST'])
def select_case():
    """Handle case selection"""
    case_id = request.form.get('case_id')
    
    # Validate case exists
    valid_case_ids = [case['case_id'] for case in AVAILABLE_CASES]
    if case_id in valid_case_ids:
        set_active_case(case_id)
        print(f"Active case set to: {case_id}")
    else:
        print(f"Invalid case ID: {case_id}")
    
    return redirect(url_for('dashboard'))

@app.route('/dashboard')
def dashboard_alt():
    """Alternative dashboard route"""
    return dashboard()

@app.route('/evidence')
def evidence():
    """Evidence integrity and hash verification route with graceful loading"""
    # Load hash data gracefully
    hash_data = load_hash_data()
    
    # Prepare evidence context
    context = {
        "hash_status": hash_data.get("status", "unknown"),
        "hash_message": hash_data.get("message", ""),
        "total_files": hash_data.get("total_files", 0) if hash_data.get("status") != "missing" else 0,
        "integrity_score": hash_data.get("integrity_score", 100) if hash_data.get("status") != "missing" else 0,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(EVIDENCE_TEMPLATE, **context)

@app.route('/timeline')
def timeline():
    """Unified timeline viewer route with graceful loading"""
    # Load timeline data gracefully
    timeline_data = load_timeline_data()
    
    # Prepare timeline context
    context = {
        "timeline_status": "loaded" if timeline_data else "missing",
        "total_events": len(timeline_data),
        "date_range_start": timeline_data[0].get("timestamp") if timeline_data else "Not available",
        "date_range_end": timeline_data[-1].get("timestamp") if timeline_data else "Not available",
        "sources": list(set(event.get("source", "Unknown") for event in timeline_data)) if timeline_data else [],
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(TIMELINE_TEMPLATE, **context)

@app.route('/report')
def report():
    """Complete forensic report viewer route with graceful loading"""
    # Load report data gracefully
    report_data = load_report_data()
    
    # Prepare report context
    context = {
        "report_status": report_data.get("status", "unknown"),
        "report_message": report_data.get("message", ""),
        "report_timestamp": report_data.get("report_metadata", {}).get("generation_timestamp", "Not generated"),
        "risk_level": report_data.get("conclusions", {}).get("overall_risk_level", "Unknown"),
        "total_events": report_data.get("timeline_summary", {}).get("total_events", 0),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(REPORT_TEMPLATE, **context)

@app.route('/download/report')
def download_report():
    """Safe download route for forensic PDF report (read-only)"""
    from flask import send_file
    
    # Try PDF first
    case_base_path = get_case_base_path()
    pdf_path = f"{case_base_path}/reports/forensic_report.pdf"
    
    if os.path.exists(pdf_path):
        try:
            active_case = get_active_case()
            return send_file(
                pdf_path,
                as_attachment=True,
                download_name=f"{active_case}_forensic_report.pdf",
                mimetype='application/pdf'
            )
        except Exception as e:
            print(f"Error serving PDF file: {e}")
            return "Error downloading PDF report", 500
    
    # Fallback to JSON if PDF not available
    json_path = f"{case_base_path}/reports/forensic_report.json"
    
    if not os.path.exists(json_path):
        return "Report not found", 404
    
    try:
        active_case = get_active_case()
        return send_file(
            json_path,
            as_attachment=True,
            download_name=f"{active_case}_forensic_report.json",
            mimetype='application/json'
        )
    except Exception as e:
        print(f"Error serving JSON file: {e}")
        return "Error downloading report", 500

@app.route('/api/status')
def api_status():
    """API endpoint for investigation status (read-only) with real integration checking"""
    # Get actual integration status
    integration_status = get_integration_status()
    
    # Load data to check actual status
    timeline_data = load_timeline_data()
    analysis_data = load_analysis_data()
    hash_data = load_hash_data()
    report_data = load_report_data()
    
    status = {
        "tool_version": "mobile-forensics-tool v1.0",
        "status": "ACTIVE",
        "timestamp": datetime.now().isoformat(),
        "integration": integration_status,
        "evidence_loaded": len(timeline_data) > 0,
        "analysis_complete": all(
            isinstance(analysis_data.get(key, []), list) and len(analysis_data.get(key, [])) > 0
            for key in ["suspicious_behaviour", "malware_indicators", "timestamp_anomalies"]
        ),
        "hash_verified": hash_data.get("status") not in ["missing", "error"],
        "report_generated": report_data.get("status") not in ["missing", "error"],
        "timeline_events": len(timeline_data),
        "completion_percentage": integration_status.get("completion_percentage", 0)
    }
    return jsonify(status)

# Robust file loading functions with graceful error handling
def load_timeline_data():
    """
    Load timeline data for display (read-only).
    
    INTEGRATOR NOTE: Run timeline/timeline_builder.py first to generate timeline.json
    
    Returns:
        - List of timeline events if file exists and is valid
        - Empty list with error logged if file missing or invalid
    """
    case_base_path = get_case_base_path()
    timeline_path = f"{case_base_path}/timeline/timeline.json"
    active_case = get_active_case()
    if not os.path.exists(timeline_path):
        print(f"Timeline not found for case {active_case}: Run timeline/timeline_builder.py first")
        return []
    
    try:
        with open(timeline_path, 'r') as f:
            data = json.load(f)
            # Validate it's a list
            if isinstance(data, list):
                print(f"Loaded {len(data)} timeline events")
                return data
            else:
                print("Invalid timeline format: Expected list of events")
                return []
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in timeline.json: {e}")
        return []
    except Exception as e:
        print(f"Error loading timeline: {e}")
        return []

def load_analysis_data():
    """
    Load analysis results for display (read-only).
    
    INTEGRATOR NOTE: Run analysis scripts first to generate findings.json
    - analysis/behaviour_analysis.py
    - analysis/malware_analysis.py  
    - analysis/anomaly_analysis.py
    - All merged into analysis/findings.json
    
    Returns:
        - Dictionary with merged analysis findings if file exists
        - Empty dictionary with status info if file missing
    """
    case_base_path = get_case_base_path()
    findings_path = f"{case_base_path}/analysis/findings.json"
    active_case = get_active_case()
    
    if not os.path.exists(findings_path):
        print(f"Merged findings not found for case {active_case}: Run analysis scripts to generate findings.json")
        return {
            "suspicious_behaviour": {"status": "missing", "message": "Analysis not completed yet"},
            "malware_indicators": {"status": "missing", "message": "Analysis not completed yet"},
            "timestamp_anomalies": {"status": "missing", "message": "Analysis not completed yet"}
        }
    
    try:
        with open(findings_path, 'r') as f:
            data = json.load(f)
            print("Loaded merged analysis findings")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in findings.json: {e}")
        return {
            "suspicious_behaviour": {"status": "error", "message": "Invalid JSON format"},
            "malware_indicators": {"status": "error", "message": "Invalid JSON format"},
            "timestamp_anomalies": {"status": "error", "message": "Invalid JSON format"}
        }
    except Exception as e:
        print(f"Error loading findings.json: {e}")
        return {
            "suspicious_behaviour": {"status": "error", "message": f"Load error: {str(e)}"},
            "malware_indicators": {"status": "error", "message": f"Load error: {str(e)}"},
            "timestamp_anomalies": {"status": "error", "message": f"Load error: {str(e)}"}
        }

def load_hash_data():
    """
    Load hash manifest for evidence integrity display (read-only).
    
    INTEGRATOR NOTE: Run analysis/hash_generator.py first to generate hashes.json
    
    Returns:
        - Hash manifest data if file exists
        - Status info if file missing
    """
    case_base_path = get_case_base_path()
    hash_path = f"{case_base_path}/evidence/hashes/hashes.json"
    active_case = get_active_case()
    if not os.path.exists(hash_path):
        print(f"Hash manifest not found for case {active_case}: Run analysis/hash_generator.py first")
        return {"status": "missing", "message": "Integrity verification pending"}
    
    try:
        with open(hash_path, 'r') as f:
            data = json.load(f)
            print(f"Loaded hash manifest with {data.get('total_files', 0)} files")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in hashes.json: {e}")
        return {"status": "error", "message": "Invalid JSON format"}
    except Exception as e:
        print(f"Error loading hash manifest: {e}")
        return {"status": "error", "message": f"Load error: {str(e)}"}

def load_report_data():
    """
    Load forensic report for display (read-only).
    
    INTEGRATOR NOTE: Run reports/generate_report.py first to generate forensic_report.json
    
    Returns:
        - Report data if file exists
        - Status info if file missing
    """
    case_base_path = get_case_base_path()
    report_path = f"{case_base_path}/reports/forensic_report.json"
    active_case = get_active_case()
    if not os.path.exists(report_path):
        print(f"Forensic report not found for case {active_case}: Run reports/generate_report.py first")
        return {"status": "missing", "message": "Report not generated yet"}
    
    try:
        with open(report_path, 'r') as f:
            data = json.load(f)
            print("Loaded forensic report")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in forensic_report.json: {e}")
        return {"status": "error", "message": "Invalid JSON format"}
    except Exception as e:
        print(f"Error loading forensic report: {e}")
        return {"status": "error", "message": f"Load error: {str(e)}"}

def get_integration_status():
    """
    Check integration status by verifying which required files exist.
    
    Returns:
        - Dictionary with status of each integration component
    """
    case_base_path = get_case_base_path()
    status = {
        "timeline": os.path.exists(f"{case_base_path}/timeline/timeline.json"),
        "findings": os.path.exists(f"{case_base_path}/analysis/findings.json"),
        "hashes": os.path.exists(f"{case_base_path}/evidence/hashes/hashes.json"),
        "forensic_report": os.path.exists(f"{case_base_path}/reports/forensic_report.json")
    }
    
    # Calculate overall completion percentage
    completed = sum(status.values())
    total = len(status)
    status["completion_percentage"] = (completed / total) * 100
    status["overall_status"] = "Ready" if completed == total else f"In Progress ({completed}/{4})"
    
    return status

def classify_case_suspicion(case_id):
    """
    Implement rule-based suspicion classification for a case.
    
    Rules (deterministic, explainable):
    - suspicious_behaviour list not empty → +1
    - timestamp_anomalies list not empty → +1
    - malware_indicators list not empty → +2
    - Activity between 00:00–04:00 detected in timeline → +1
    
    Classification:
    - 0 points → Clean
    - 1–2 points → Suspicious
    - ≥3 points → Highly Suspicious
    
    Args:
        case_id: Case identifier
        
    Returns:
        dict: Suspicion classification with reasons
    """
    case_base_path = f"../cases/{case_id}"
    
    # Load analysis findings
    findings_path = f"{case_base_path}/analysis/findings.json"
    findings = {}
    reasons = []
    score = 0
    
    if os.path.exists(findings_path):
        try:
            with open(findings_path, 'r') as f:
                findings = json.load(f)
        except Exception as e:
            print(f"Error loading findings for case {case_id}: {e}")
    
    # Rule 1: suspicious_behaviour not empty → +1
    suspicious_behaviour = findings.get("suspicious_behaviour", [])
    if suspicious_behaviour and len(suspicious_behaviour) > 0:
        score += 1
        reasons.append(f"Suspicious behaviour indicators present ({len(suspicious_behaviour)} patterns)")
    
    # Rule 2: timestamp_anomalies not empty → +1
    timestamp_anomalies = findings.get("timestamp_anomalies", [])
    if timestamp_anomalies and len(timestamp_anomalies) > 0:
        score += 1
        reasons.append(f"Timestamp anomalies detected ({len(timestamp_anomalies)} anomalies)")
    
    # Rule 3: malware_indicators not empty → +2
    malware_indicators = findings.get("malware_indicators", [])
    if malware_indicators and len(malware_indicators) > 0:
        score += 2
        reasons.append(f"Malware indicators present ({len(malware_indicators)} indicators)")
    
    # Rule 4: Late-night activity (00:00–04:00) → +1
    timeline_path = f"{case_base_path}/timeline/timeline.json"
    late_night_activity = False
    
    if os.path.exists(timeline_path):
        try:
            with open(timeline_path, 'r') as f:
                timeline = json.load(f)
                
            for event in timeline:
                timestamp = event.get("timestamp", "")
                if timestamp:
                    try:
                        # Extract hour from timestamp
                        hour = int(timestamp.split(" ")[1].split(":")[0])
                        if 0 <= hour <= 3:  # 00:00-03:59
                            late_night_activity = True
                            break
                    except (ValueError, IndexError):
                        continue
                        
            if late_night_activity:
                score += 1
                reasons.append("Late-night activity detected (00:00-04:00)")
                
        except Exception as e:
            print(f"Error loading timeline for case {case_id}: {e}")
    
    # Classification
    if score == 0:
        suspicion_level = "Clean"
    elif score <= 2:
        suspicion_level = "Suspicious"
    else:
        suspicion_level = "Highly Suspicious"
    
    classification = {
        "suspicion_level": suspicion_level,
        "score": score,
        "reasons": reasons,
        "classification_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    # Save classification to case_status.json
    status_path = f"{case_base_path}/analysis/case_status.json"
    try:
        os.makedirs(os.path.dirname(status_path), exist_ok=True)
        with open(status_path, 'w') as f:
            json.dump(classification, f, indent=2)
        print(f"Saved suspicion classification for case {case_id}: {suspicion_level} (score: {score})")
    except Exception as e:
        print(f"Error saving case status for {case_id}: {e}")
    
    return classification

def load_case_suspicion(case_id):
    """
    Load existing suspicion classification or generate new one.
    
    Args:
        case_id: Case identifier
        
    Returns:
        dict: Suspicion classification
    """
    status_path = f"../cases/{case_id}/analysis/case_status.json"
    
    if os.path.exists(status_path):
        try:
            with open(status_path, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading case status for {case_id}: {e}")
    
    # Generate new classification if not exists
    return classify_case_suspicion(case_id)

def load_case_metadata():
    """
    Load case metadata for dashboard display (read-only).
    
    Returns:
        - Case metadata dictionary if file exists
        - Default metadata if file missing
    """
    case_base_path = get_case_base_path()
    metadata_path = f"{case_base_path}/metadata.json"
    active_case = get_active_case()
    
    if not os.path.exists(metadata_path):
        print(f"Case metadata not found for case {active_case}")
        return {
            "case_id": "UNKNOWN",
            "case_name": "Unknown Case",
            "investigator": "Unknown Investigator",
            "data_source": "Unknown Source",
            "device_type": "Unknown Device",
            "case_status": "Unknown"
        }
    
    try:
        with open(metadata_path, 'r') as f:
            data = json.load(f)
            print(f"Loaded case metadata for {data.get('case_id', 'UNKNOWN')}")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in metadata.json: {e}")
        return {
            "case_id": "ERROR",
            "case_name": "Error Loading Case",
            "investigator": "Error",
            "data_source": "Error",
            "device_type": "Error",
            "case_status": "Error"
        }
    except Exception as e:
        print(f"Error loading case metadata: {e}")
        return {
            "case_id": "ERROR",
            "case_name": "Error Loading Case",
            "investigator": "Error",
            "data_source": "Error",
            "device_type": "Error",
            "case_status": "Error"
        }

if __name__ == '__main__':
    print("Starting Mobile Forensics Tool - Secure Read-Only Web Viewer")
    print("SECURITY NOTICE: This is a READ-ONLY interface for forensic evidence viewing")
    print("No evidence modification is possible through this interface")
    print("Access: http://localhost:5000")
    
    # Run Flask app in debug mode for development
    app.run(debug=True, host='0.0.0.0', port=5000)
