"""
Secure Read-Only Web Viewer for Mobile Forensics Investigation Tool

FORENSIC ROLE:
- Provides secure, read-only web interface for forensic evidence viewing
- Displays investigation results without allowing evidence modification
- Ensures chain of custody integrity (no POST operations)
- Presents timeline, analysis findings, and reports in web format

SECURITY CONSTRAINTS:
- READ-ONLY interface (no POST, PUT, DELETE operations)
- No evidence modification capabilities
- No file upload or download features
- Session-based viewing only
- All data displayed is pre-processed and static

INTEGRATION NOTES:
- This UI only DISPLAYS pre-generated JSON files
- INTEGRATOR RESPONSIBILITY: Run extraction/analysis scripts first
- Gracefully handles missing files with clear status messages
- Never crashes - always shows meaningful status
- File paths are relative to ui/ directory

ROUTES:
- / : Main dashboard with investigation overview
- /dashboard : Investigation summary and statistics
- /evidence : Evidence integrity and hash verification
- /timeline : Unified timeline viewer
- /report : Complete forensic report viewer

EXPECTED FILE STRUCTURE (for integration):
../timeline/timeline.json                    # Generated by timeline/timeline_builder.py
../analysis/findings.json                    # Merged findings from all analysis scripts
../evidence/hashes/hashes.json               # Generated by analysis/hash_generator.py
../reports/forensic_report.json             # Generated by reports/generate_report.py (preview)
"""

from flask import Flask, render_template_string, jsonify, request, redirect, url_for, session
import json
import os
from datetime import datetime

app = Flask(__name__)
app.secret_key = 'forensic-session-key'  # Required for session management

# Multi-case forensic investigation setup
def discover_cases():
    """
    Discover all valid cases in the cases/ directory.
    
    A valid case must contain:
    - metadata.json
    - evidence/
    - analysis/findings.json
    - timeline/timeline.json
    - reports/forensic_report.pdf
    
    Returns:
        list: List of valid case dictionaries
    """
    cases_dir = "../cases"
    valid_cases = []
    
    if not os.path.exists(cases_dir):
        print(f"Cases directory not found: {cases_dir}")
        return valid_cases
    
    for case_id in os.listdir(cases_dir):
        case_path = os.path.join(cases_dir, case_id)
        
        # Skip non-directories
        if not os.path.isdir(case_path):
            continue
        
        # Validate case structure
        required_files = [
            os.path.join(case_path, "metadata.json"),
            os.path.join(case_path, "evidence"),
            os.path.join(case_path, "analysis", "findings.json"),
            os.path.join(case_path, "timeline", "timeline.json"),
            os.path.join(case_path, "reports", "forensic_report.pdf")
        ]
        
        if all(os.path.exists(path) for path in required_files):
            # Load case metadata
            try:
                metadata_path = os.path.join(case_path, "metadata.json")
                with open(metadata_path, 'r') as f:
                    metadata = json.load(f)
                
                case_info = {
                    "case_id": case_id,
                    "device_model": metadata.get("device_type", "Unknown"),
                    "dataset_source": metadata.get("data_source", "Unknown"),
                    "case_name": metadata.get("case_name", case_id),
                    "investigator": metadata.get("investigator", "Unknown")
                }
                valid_cases.append(case_info)
                print(f"Discovered valid case: {case_id}")
                
            except Exception as e:
                print(f"Error loading metadata for case {case_id}: {e}")
        else:
            print(f"Case {case_id} missing required files, skipping")
    
    return valid_cases

# Global case discovery
AVAILABLE_CASES = discover_cases()
DEFAULT_CASE = AVAILABLE_CASES[0]["case_id"] if AVAILABLE_CASES else "case_001"

# Session-based active case management
def get_active_case():
    """Get the currently active case from session or default"""
    return session.get('active_case', DEFAULT_CASE)

def set_active_case(case_id):
    """Set the active case in session"""
    session['active_case'] = case_id

def get_case_base_path():
    """Get the base path for the active case"""
    active_case = get_active_case()
    return f"../cases/{active_case}"

# HTML templates for each route
DASHBOARD_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Dashboard</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; color: #2c3e50; border-bottom: 3px solid #007bff; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
        .header h2 { margin: 10px 0 0 0; font-size: 16px; color: #6c757d; font-weight: 400; }
        .nav { margin: 25px 0; text-align: center; }
        .nav a { margin: 0 10px; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 6px; font-weight: 500; transition: background 0.3s; }
        .nav a:hover { background: #0056b3; }
        .section { margin: 25px 0; padding: 20px; border-radius: 8px; border-left: 4px solid; }
        .section-case { background: #e7f3ff; border-color: #007bff; }
        .section-status { background: #d4edda; border-color: #28a745; }
        .section-pipeline { background: #fff3cd; border-color: #ffc107; }
        .section-overview { background: #f8f9fa; border-color: #6c757d; }
        .section h3 { margin: 0 0 15px 0; color: #2c3e50; font-size: 18px; font-weight: 600; }
        .section p { margin: 8px 0; line-height: 1.5; }
        .case-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .case-item { background: white; padding: 12px; border-radius: 6px; border: 1px solid #dee2e6; }
        .case-item strong { color: #495057; display: block; margin-bottom: 4px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .case-item span { color: #212529; font-size: 14px; }
        .suspicion-badge { display: inline-block; padding: 6px 12px; border-radius: 20px; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
        .suspicion-clean { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .suspicious { background: #fff3cd; color: #856404; border: 1px solid #ffeaa7; }
        .highly-suspicious { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .reasons-list { margin: 10px 0; padding-left: 20px; }
        .reasons-list li { margin: 5px 0; color: #495057; }
        .progress-bar { width: 100%; height: 24px; background: #e9ecef; border-radius: 12px; overflow: hidden; margin: 10px 0; }
        .progress-fill { height: 100%; background: linear-gradient(90deg, #28a745, #20c997); transition: width 0.3s ease; display: flex; align-items: center; justify-content: center; color: white; font-size: 12px; font-weight: 600; }
        .component-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 15px 0; }
        .component-item { display: flex; align-items: center; padding: 8px; background: white; border-radius: 6px; }
        .component-status { margin-right: 8px; font-size: 16px; }
        .forensic-note { background: #e7f3ff; border: 1px solid #b3d9ff; padding: 15px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #004085; }
        .case-selector { margin: 15px 0; }
        .case-selector select { width: 100%; max-width: 400px; padding: 10px; border: 2px solid #dee2e6; border-radius: 6px; font-size: 14px; background: white; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Secure Read-Only Evidence Viewer | Judicial Review Interface</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        <!-- Case Overview Section -->
        <div class="section section-case">
            <h3>📋 Case Overview</h3>
            <div class="case-grid">
                <div class="case-item">
                    <strong>Case ID</strong>
                    <span>{{ case_metadata.case_id }}</span>
                </div>
                <div class="case-item">
                    <strong>Investigator</strong>
                    <span>{{ case_metadata.investigator }}</span>
                </div>
                <div class="case-item">
                    <strong>Device / Dataset Source</strong>
                    <span>{{ case_metadata.device_type }}</span>
                </div>
                <div class="case-item">
                    <strong>Acquisition Method</strong>
                    <span>{{ case_metadata.acquisition_method }}</span>
                </div>
                <div class="case-item">
                    <strong>Dataset Source</strong>
                    <span>{{ case_metadata.dataset_source }}</span>
                </div>
                <div class="case-item">
                    <strong>Case Created</strong>
                    <span>{{ case_metadata.created_at }}</span>
                </div>
            </div>
        </div>
        
        <!-- Case Status Section -->
        <div class="section section-status">
            <h3>🔍 Case Status</h3>
            {% if case_suspicion and case_suspicion.suspicion_level %}
            <div class="case-grid">
                <div class="case-item">
                    <strong>Suspicion Level</strong>
                    <span class="suspicion-badge {% if case_suspicion.suspicion_level == 'Clean' %}suspicion-clean{% elif case_suspicion.suspicion_level == 'Suspicious' %}suspicious{% else %}highly-suspicious{% endif %}">
                        {{ case_suspicion.suspicion_level }} (Score: {{ case_suspicion.score }})
                    </span>
                </div>
                <div class="case-item">
                    <strong>Risk Assessment</strong>
                    <span>{{ case_suspicion.score }}/5 - Rule-based classification</span>
                </div>
            </div>
            
            {% if case_suspicion.reasons %}
            <div>
                <strong>Classification Reasons:</strong>
                <ul class="reasons-list">
                    {% for reason in case_suspicion.reasons %}
                    <li>{{ reason }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% else %}
            <div class="case-item">
                <strong>Suspicion Classification</strong>
                <span>Suspicion classification not available for this case</span>
            </div>
            {% endif %}
        </div>
        
        <!-- Pipeline Status Section -->
        <div class="section section-pipeline">
            <h3>⚙️ Pipeline Status</h3>
            <div class="component-grid">
                <div class="component-item">
                    <span class="component-status">{{ "✅" if pipeline_status.raw_evidence else "❌" }}</span>
                    <span>Raw Evidence Available</span>
                </div>
                <div class="component-item">
                    <span class="component-status">{{ "✅" if pipeline_status.hash_manifest else "❌" }}</span>
                    <span>Hash Manifest Available</span>
                </div>
                <div class="component-item">
                    <span class="component-status">{{ "✅" if pipeline_status.analysis_completed else "❌" }}</span>
                    <span>Analysis Completed</span>
                </div>
                <div class="component-item">
                    <span class="component-status">{{ "✅" if pipeline_status.timeline_generated else "❌" }}</span>
                    <span>Timeline Generated</span>
                </div>
                <div class="component-item">
                    <span class="component-status">{{ "✅" if pipeline_status.pdf_report_available else "❌" }}</span>
                    <span>PDF Report Available</span>
                </div>
            </div>
        </div>
        
        <!-- Case Selection Section -->
        <div class="section section-overview">
            <h3>🔄 Case Selection</h3>
            <form method="POST" action="/select_case" class="case-selector">
                <label for="case_select"><strong>Select Active Case:</strong></label>
                <select id="case_select" name="case_id" onchange="this.form.submit()">
                    {% for case in available_cases %}
                    <option value="{{ case.case_id }}" {% if case.case_id == active_case %}selected{% endif %}>
                        {{ case.case_id }} - {{ case.case_name }}
                    </option>
                    {% endfor %}
                </select>
            </form>
            
            <div class="forensic-note">
                <strong>🔒 Forensic Notice:</strong> All evidence, timeline, and reports displayed belong exclusively to the active case. This interface maintains strict read-only access with complete case isolation.
            </div>
        </div>
    </div>
</body>
</html>
"""

EVIDENCE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Evidence</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; color: #2c3e50; border-bottom: 3px solid #28a745; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
        .header h2 { margin: 10px 0 0 0; font-size: 16px; color: #6c757d; font-weight: 400; }
        .nav { margin: 25px 0; text-align: center; }
        .nav a { margin: 0 10px; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 6px; font-weight: 500; transition: background 0.3s; }
        .nav a:hover { background: #0056b3; }
        .section { margin: 25px 0; padding: 20px; border-radius: 8px; border-left: 4px solid; }
        .section-integrity { background: #d4edda; border-color: #28a745; }
        .section-warning { background: #fff3cd; border-color: #ffc107; }
        .section-error { background: #f8d7da; border-color: #dc3545; }
        .section-info { background: #d1ecf1; border-color: #17a2b8; }
        .section h3 { margin: 0 0 15px 0; color: #2c3e50; font-size: 18px; font-weight: 600; }
        .section p { margin: 8px 0; line-height: 1.5; }
        .evidence-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .evidence-item { background: white; padding: 12px; border-radius: 6px; border: 1px solid #dee2e6; }
        .evidence-item strong { color: #495057; display: block; margin-bottom: 4px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .evidence-item span { color: #212529; font-size: 14px; }
        .integrity-badge { display: inline-block; padding: 6px 12px; border-radius: 20px; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
        .integrity-verified { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .integrity-pending { background: #fff3cd; color: #856404; border: 1px solid #ffeaa7; }
        .integrity-error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .forensic-note { background: #e7f3ff; border: 1px solid #b3d9ff; padding: 15px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #004085; }
        .code-block { background: #f8f9fa; border: 1px solid #e9ecef; padding: 8px 12px; border-radius: 4px; font-family: 'Courier New', monospace; font-size: 13px; color: #495057; }
        .steps-list { margin: 15px 0; padding-left: 20px; }
        .steps-list li { margin: 8px 0; color: #495057; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Evidence Integrity & Chain of Custody Verification</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if hash_status == "missing" %}
        <div class="section section-warning">
            <h3>⚠️ Evidence Integrity Status</h3>
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Chain of Custody</strong>
                    <span>Not Established</span>
                </div>
                <div class="evidence-item">
                    <strong>Hash Verification</strong>
                    <span>{{ hash_message }}</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge integrity-pending">Verification Required</span>
            </div>
        </div>
        {% elif hash_status == "error" %}
        <div class="section section-error">
            <h3>❌ Evidence Integrity Error</h3>
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Chain of Custody</strong>
                    <span>Error Detected</span>
                </div>
                <div class="evidence-item">
                    <strong>Hash Verification</strong>
                    <span>{{ hash_message }}</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge integrity-error">Integrity Compromised</span>
            </div>
        </div>
        {% else %}
        <div class="section section-integrity">
            <h3>✅ Evidence Integrity Status</h3>
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Chain of Custody</strong>
                    <span>Maintained & Verified</span>
                </div>
                <div class="evidence-item">
                    <strong>Hash Algorithm</strong>
                    <span>SHA-256 Cryptographic Verification</span>
                </div>
                <div class="evidence-item">
                    <strong>Total Files Processed</strong>
                    <span>{{ total_files }} evidence files</span>
                </div>
                <div class="evidence-item">
                    <strong>Integrity Score</strong>
                    <span>{{ "%.1f"|format(integrity_score) }}% Verified</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge integrity-verified">Forensically Verified</span>
            </div>
        </div>
        {% endif %}
        
        <!-- Raw Evidence Section -->
        <div class="section section-info">
            <h3>� Raw Evidence</h3>
            {% if evidence_info.raw_evidence.available %}
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Total Files</strong>
                    <span>{{ evidence_info.raw_evidence.file_count }} files</span>
                </div>
                <div class="evidence-item">
                    <strong>Total Size</strong>
                    <span>{{ evidence_info.raw_evidence.total_size_mb }} MB</span>
                </div>
            </div>
            {% else %}
            <div class="evidence-item">
                <strong>Raw Evidence Status</strong>
                <span>Raw evidence not available for this case</span>
            </div>
            {% endif %}
        </div>
        
        <!-- Hash Verification Section -->
        <div class="section {% if evidence_info.hash_verification.available %}section-integrity{% else %}section-warning{% endif %}">
            <h3>🔒 Hash Verification</h3>
            {% if evidence_info.hash_verification.available %}
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Hash Algorithm</strong>
                    <span>{{ evidence_info.hash_verification.algorithm }}</span>
                </div>
                <div class="evidence-item">
                    <strong>Files Hashed</strong>
                    <span>{{ evidence_info.hash_verification.files_hashed }} files</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge integrity-verified">{{ evidence_info.hash_verification.status }}</span>
            </div>
            {% else %}
            <div class="evidence-item">
                <strong>Hash Verification Status</strong>
                <span>Hash verification not yet generated for this case</span>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge integrity-pending">Not Generated</span>
            </div>
            {% endif %}
        </div>
        
        <!-- Processed Evidence Section -->
        <div class="section section-info">
            <h3>⚙️ Processed Evidence</h3>
            <div class="evidence-grid">
                {% if evidence_info.processed_evidence.sms.available %}
                <div class="evidence-item">
                    <strong>SMS Messages</strong>
                    <span>{{ evidence_info.processed_evidence.sms.count }} messages</span>
                </div>
                {% endif %}
                {% if evidence_info.processed_evidence.calls.available %}
                <div class="evidence-item">
                    <strong>Call Records</strong>
                    <span>{{ evidence_info.processed_evidence.calls.count }} calls</span>
                </div>
                {% endif %}
                {% if evidence_info.processed_evidence.media.available %}
                <div class="evidence-item">
                    <strong>Media Files</strong>
                    <span>{{ evidence_info.processed_evidence.media.count }} items</span>
                </div>
                {% endif %}
                {% if evidence_info.processed_evidence.apps.available %}
                <div class="evidence-item">
                    <strong>App Artifacts</strong>
                    <span>{{ evidence_info.processed_evidence.apps.count }} artifacts</span>
                </div>
                {% endif %}
            </div>
        </div>
        
        <!-- Chain of Custody Section -->
        <div class="section section-info">
            <h3>⚖️ Chain of Custody</h3>
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Acquisition Method</strong>
                    <span>{{ case_metadata.acquisition_method }}</span>
                </div>
                <div class="evidence-item">
                    <strong>Storage Location</strong>
                    <span>Isolated case directory: cases/{{ active_case }}/</span>
                </div>
                <div class="evidence-item">
                    <strong>Preservation Method</strong>
                    <span>Read-only access with cryptographic verification</span>
                </div>
                <div class="evidence-item">
                    <strong>Integrity Verification</strong>
                    <span>{% if evidence_info.hash_verification.available %}SHA-256 Verified{% else %}Not Available{% endif %}</span>
                </div>
            </div>
        </div>
        
        <!-- Evidence Overview Summary -->
        <div class="section {% if forensic_readiness == 'Complete' %}section-integrity{% elif forensic_readiness == 'Partial' %}section-warning{% else %}section-error{% endif %}">
            <h3>📊 Evidence Overview Summary</h3>
            <div class="evidence-grid">
                <div class="evidence-item">
                    <strong>Total Evidence Files</strong>
                    <span>{{ total_evidence_files }} files</span>
                </div>
                <div class="evidence-item">
                    <strong>Integrity Status</strong>
                    <span>{% if evidence_info.hash_verification.available %}Verified{% else %}Not Verified{% endif %}</span>
                </div>
                <div class="evidence-item">
                    <strong>Forensic Readiness</strong>
                    <span>{{ forensic_readiness }}</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="integrity-badge {% if forensic_readiness == 'Complete' %}integrity-verified{% elif forensic_readiness == 'Partial' %}integrity-pending{% else %}integrity-error{% endif %}">
                    {{ forensic_readiness }}
                </span>
            </div>
        </div>
    </div>
</body>
</html>
"""

TIMELINE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Timeline</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; color: #2c3e50; border-bottom: 3px solid #17a2b8; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
        .header h2 { margin: 10px 0 0 0; font-size: 16px; color: #6c757d; font-weight: 400; }
        .nav { margin: 25px 0; text-align: center; }
        .nav a { margin: 0 10px; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 6px; font-weight: 500; transition: background 0.3s; }
        .nav a:hover { background: #0056b3; }
        .section { margin: 25px 0; padding: 20px; border-radius: 8px; border-left: 4px solid; }
        .section-info { background: #d1ecf1; border-color: #17a2b8; }
        .section-success { background: #d4edda; border-color: #28a745; }
        .section-warning { background: #fff3cd; border-color: #ffc107; }
        .section h3 { margin: 0 0 15px 0; color: #2c3e50; font-size: 18px; font-weight: 600; }
        .section p { margin: 8px 0; line-height: 1.5; }
        .timeline-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .timeline-item { background: white; padding: 12px; border-radius: 6px; border: 1px solid #dee2e6; }
        .timeline-item strong { color: #495057; display: block; margin-bottom: 4px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .timeline-item span { color: #212529; font-size: 14px; }
        .event-list { max-height: 500px; overflow-y: auto; border: 1px solid #dee2e6; border-radius: 6px; background: #f8f9fa; }
        .event-item { padding: 12px; border-bottom: 1px solid #dee2e6; display: flex; align-items: flex-start; }
        .event-item:last-child { border-bottom: none; }
        .event-item:hover { background: #e9ecef; }
        .event-icon { width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 12px; font-size: 12px; font-weight: bold; color: white; flex-shrink: 0; }
        .icon-sms { background: #007bff; }
        .icon-call { background: #28a745; }
        .icon-media { background: #ffc107; color: #212529; }
        .icon-app { background: #6f42c1; }
        .event-content { flex: 1; }
        .event-time { font-size: 12px; color: #6c757d; font-weight: 600; margin-bottom: 4px; }
        .event-details { font-size: 14px; color: #212529; line-height: 1.4; }
        .event-type { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 10px; font-weight: 600; text-transform: uppercase; margin-left: 8px; }
        .type-sms { background: #007bff; color: white; }
        .type-call { background: #28a745; color: white; }
        .type-media { background: #ffc107; color: #212529; }
        .type-app { background: #6f42c1; color: white; }
        .forensic-note { background: #e7f3ff; border: 1px solid #b3d9ff; padding: 15px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #004085; }
        .code-block { background: #f8f9fa; border: 1px solid #e9ecef; padding: 8px 12px; border-radius: 4px; font-family: 'Courier New', monospace; font-size: 13px; color: #495057; }
        .steps-list { margin: 15px 0; padding-left: 20px; }
        .steps-list li { margin: 8px 0; color: #495057; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Unified Event Timeline Reconstruction | Chronological Evidence Analysis</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if timeline_status == "missing" %}
        <div class="section section-warning">
            <h3>⚠️ Timeline Not Available</h3>
            <div class="timeline-grid">
                <div class="timeline-item">
                    <strong>Reconstruction Status</strong>
                    <span>Timeline not generated yet</span>
                </div>
                <div class="timeline-item">
                    <strong>Total Events</strong>
                    <span>0 events processed</span>
                </div>
            </div>
        </div>
        {% else %}
        <div class="section section-success">
            <h3>📊 Timeline Reconstruction Summary</h3>
            <div class="timeline-grid">
                <div class="timeline-item">
                    <strong>Total Events</strong>
                    <span>{{ total_events }} chronologically ordered events</span>
                </div>
                <div class="timeline-item">
                    <strong>Date Range</strong>
                    <span>{{ date_range_start }} to {{ date_range_end }}</span>
                </div>
                <div class="timeline-item">
                    <strong>Data Sources</strong>
                    <span>{{ sources|join(', ') if sources else 'No sources detected' }}</span>
                </div>
                <div class="timeline-item">
                    <strong>Last Updated</strong>
                    <span>{{ timestamp }}</span>
                </div>
            </div>
        </div>
        {% endif %}
        
        <!-- Timeline Summary Section -->
        <div class="section section-info">
            <h3>� Timeline Summary</h3>
            <div class="timeline-grid">
                <div class="timeline-item">
                    <strong>Total Events</strong>
                    <span>{{ total_events }} chronologically ordered events</span>
                </div>
                <div class="timeline-item">
                    <strong>Time Range</strong>
                    <span>{{ date_range_start }} to {{ date_range_end }}</span>
                </div>
                <div class="timeline-item">
                    <strong>Data Sources</strong>
                    <span>{{ sources|join(', ') if sources else 'No sources detected' }}</span>
                </div>
                <div class="timeline-item">
                    <strong>Timestamp Anomalies</strong>
                    <span>{{ anomaly_count }} anomalies detected</span>
                </div>
            </div>
        </div>
        
        {% if timeline_status == "missing" %}
        <div class="section section-warning">
            <h3>🔧 Required Actions</h3>
            <p>To generate the unified timeline, complete the forensic pipeline:</p>
            <ol class="steps-list">
                <li>Extract evidence: <span class="code-block">cd extractor && python extract_*.py</span></li>
                <li>Run analysis: <span class="code-block">cd analysis && python *_analysis.py</span></li>
                <li>Build timeline: <span class="code-block">cd timeline && python build_timeline.py</span></li>
                <li>Refresh this page to view reconstructed timeline</li>
            </ol>
        </div>
        {% else %}
        <div class="section section-info">
            <h3>📅 Chronological Events</h3>
            <div class="event-list">
                {% for event in events %}
                <div class="event-item">
                    <div class="event-icon {% if event.source == 'SMS' %}icon-sms{% elif event.source == 'CALL' %}icon-call{% elif event.source == 'MEDIA' %}icon-media{% else %}icon-app{% endif %}">
                        {% if event.source == 'SMS' %}💬{% elif event.source == 'CALL' %}📞{% elif event.source == 'MEDIA' %}📷{% else %}📱{% endif %}
                    </div>
                    <div class="event-content">
                        <div class="event-time">
                            {{ event.timestamp }}
                            <span class="event-type {% if event.source == 'SMS' %}type-sms{% elif event.source == 'CALL' %}type-call{% elif event.source == 'MEDIA' %}type-media{% else %}type-app{% endif %}">
                                {{ event.source }}
                            </span>
                        </div>
                        <div class="event-details">{{ event.details }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</body>
</html>
"""

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Mobile Forensics Tool - Report</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; color: #2c3e50; border-bottom: 3px solid #dc3545; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
        .header h2 { margin: 10px 0 0 0; font-size: 16px; color: #6c757d; font-weight: 400; }
        .nav { margin: 25px 0; text-align: center; }
        .nav a { margin: 0 10px; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 6px; font-weight: 500; transition: background 0.3s; }
        .nav a:hover { background: #0056b3; }
        .section { margin: 25px 0; padding: 20px; border-radius: 8px; border-left: 4px solid; }
        .section-success { background: #d4edda; border-color: #28a745; }
        .section-warning { background: #fff3cd; border-color: #ffc107; }
        .section-error { background: #f8d7da; border-color: #dc3545; }
        .section-info { background: #d1ecf1; border-color: #17a2b8; }
        .section h3 { margin: 0 0 15px 0; color: #2c3e50; font-size: 18px; font-weight: 600; }
        .section p { margin: 8px 0; line-height: 1.5; }
        .report-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }
        .report-item { background: white; padding: 12px; border-radius: 6px; border: 1px solid #dee2e6; }
        .report-item strong { color: #495057; display: block; margin-bottom: 4px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
        .report-item span { color: #212529; font-size: 14px; }
        .report-badge { display: inline-block; padding: 6px 12px; border-radius: 20px; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
        .report-complete { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .report-pending { background: #fff3cd; color: #856404; border: 1px solid #ffeaa7; }
        .report-error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .download-btn { background: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: 600; transition: background 0.3s; }
        .download-btn:hover { background: #218838; }
        .forensic-note { background: #e7f3ff; border: 1px solid #b3d9ff; padding: 15px; border-radius: 6px; margin: 20px 0; font-size: 13px; color: #004085; }
        .code-block { background: #f8f9fa; border: 1px solid #e9ecef; padding: 8px 12px; border-radius: 4px; font-family: 'Courier New', monospace; font-size: 13px; color: #495057; }
        .steps-list { margin: 15px 0; padding-left: 20px; }
        .steps-list li { margin: 8px 0; color: #495057; }
        .contents-list { margin: 15px 0; padding-left: 20px; }
        .contents-list li { margin: 8px 0; color: #495057; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Mobile Forensics Investigation Tool</h1>
            <h2>Comprehensive Forensic Report | Judicial Review Documentation</h2>
        </div>
        
        <div class="nav">
            <a href="/">Dashboard</a>
            <a href="/evidence">Evidence</a>
            <a href="/timeline">Timeline</a>
            <a href="/report">Report</a>
        </div>
        
        {% if report_status == "missing" %}
        <div class="section section-warning">
            <h3>⚠️ Forensic Report Not Available</h3>
            <div class="report-grid">
                <div class="report-item">
                    <strong>Report Generation Status</strong>
                    <span>{{ report_message }}</span>
                </div>
                <div class="report-item">
                    <strong>Court Readiness</strong>
                    <span>Not Available - Analysis Incomplete</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="report-badge report-pending">Generation Required</span>
            </div>
        </div>
        {% elif report_status == "error" %}
        <div class="section section-error">
            <h3>❌ Report Generation Error</h3>
            <div class="report-grid">
                <div class="report-item">
                    <strong>Error Status</strong>
                    <span>Report generation failed</span>
                </div>
                <div class="report-item">
                    <strong>Error Details</strong>
                    <span>{{ report_message }}</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="report-badge report-error">Generation Failed</span>
            </div>
        </div>
        {% else %}
        <div class="section section-success">
            <h3>✅ Forensic Report Summary</h3>
            <div class="report-grid">
                <div class="report-item">
                    <strong>Report Status</strong>
                    <span>Complete - Court Ready</span>
                </div>
                <div class="report-item">
                    <strong>Risk Assessment</strong>
                    <span>{{ risk_level }} Level Detected</span>
                </div>
                <div class="report-item">
                    <strong>Events Analyzed</strong>
                    <span>{{ total_events }} timeline events processed</span>
                </div>
                <div class="report-item">
                    <strong>Generation Timestamp</strong>
                    <span>{{ report_timestamp }}</span>
                </div>
            </div>
            <div style="margin: 15px 0;">
                <span class="report-badge report-complete">Forensically Verified</span>
            </div>
        </div>
        {% endif %}
        
        <!-- Report Overview Section -->
        <div class="section section-info">
            <h3>📋 Forensic Report Overview</h3>
            <p><strong>Report Purpose:</strong> This comprehensive forensic report documents the complete analysis of digital evidence from acquisition to final findings.</p>
            <p><strong>Scope:</strong> Includes timeline reconstruction, behavioral analysis, malware detection, anomaly identification, and evidence integrity verification.</p>
            <p><strong>Court Readiness:</strong> Maintains complete chain of custody with cryptographic verification and forensic best practices.</p>
            
            <div class="forensic-note">
                <strong>⚖️ Judicial Review Status:</strong> This report is prepared for legal proceedings and maintains forensic admissibility standards with complete audit trails.
            </div>
        </div>
        
        {% if report_status == "missing" %}
        <div class="section section-warning">
            <h3>🔧 Required Actions</h3>
            <p>To generate the comprehensive forensic report, complete the analysis pipeline:</p>
            <ol class="steps-list">
                <li>Complete evidence extraction: <span class="code-block">cd extractor && python extract_*.py</span></li>
                <li>Run forensic analysis: <span class="code-block">cd analysis && python *_analysis.py</span></li>
                <li>Build timeline: <span class="code-block">cd timeline && python build_timeline.py</span></li>
                <li>Generate report: <span class="code-block">cd reports && python generate_case_report.py</span></li>
                <li>Refresh this page to access the completed report</li>
            </ol>
        </div>
        {% else %}
        <div class="section section-success">
            <h3>📄 Report Contents & Documentation</h3>
            <p><strong>Comprehensive Analysis Includes:</strong></p>
            <ul class="contents-list">
                <li><strong>Evidence Integrity:</strong> SHA-256 cryptographic verification and chain of custody documentation</li>
                <li><strong>Timeline Reconstruction:</strong> Chronological event analysis from multiple evidence sources</li>
                <li><strong>Behavioral Analysis:</strong> Pattern detection and suspicious activity identification</li>
                <li><strong>Malware Analysis:</strong> Security indicator detection and threat assessment</li>
                <li><strong>Anomaly Detection:</strong> Temporal inconsistency and unusual pattern analysis</li>
                <li><strong>Risk Assessment:</strong> Executive summary with evidence-based conclusions</li>
                <li><strong>Technical Appendix:</strong> Detailed methodology and forensic process documentation</li>
            </ul>
            
            <div class="forensic-note">
                <strong>🔒 Forensic Guarantee:</strong> This report maintains complete evidence integrity with verifiable chain of custody, cryptographic hashes, and court-admissible documentation standards.
            </div>
        </div>
        {% endif %}
        
        <!-- Evidence & Events Summary Section -->
        <div class="section section-info">
            <h3>📊 Evidence & Events Summary</h3>
            <div class="report-grid">
                <div class="report-item">
                    <strong>Call Records</strong>
                    <span>{{ evidence_counts.calls }} calls analyzed</span>
                </div>
                <div class="report-item">
                    <strong>Messages</strong>
                    <span>{{ evidence_counts.messages }} messages analyzed</span>
                </div>
                <div class="report-item">
                    <strong>Media Files</strong>
                    <span>{{ evidence_counts.media }} media items analyzed</span>
                </div>
                <div class="report-item">
                    <strong>App Artifacts</strong>
                    <span>{{ evidence_counts.apps }} app artifacts analyzed</span>
                </div>
            </div>
            
            <div style="margin-top: 20px; text-align: center;">
                <a href="/timeline" style="background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; display: inline-block; margin-right: 10px;">
                    📅 View Timeline Analysis
                </a>
                <p style="margin-top: 10px; font-size: 13px; color: #6c757d;">
                    Detailed chronological reconstruction of all events
                </p>
            </div>
        </div>
        
        <!-- Report Access Section -->
        <div class="section {% if report_status == 'missing' %}section-warning{% else %}section-success{% endif %}">
            <h3>📥 Report Access</h3>
            {% if report_status == "missing" %}
            <div class="report-item">
                <strong>Report Status</strong>
                <span>Report not generated for this case</span>
            </div>
            {% else %}
            <div class="report-grid">
                <div class="report-item">
                    <strong>Report Format</strong>
                    <span>Court-ready PDF document</span>
                </div>
                <div class="report-item">
                    <strong>Access Level</strong>
                    <span>Read-only forensic review</span>
                </div>
            </div>
            
            <div style="margin-top: 25px; text-align: center;">
                <a href="/download/report" download="forensic_report.pdf" class="download-btn">
                    📥 Download Complete Forensic Report (PDF)
                </a>
                <p style="margin-top: 10px; font-size: 13px; color: #6c757d;">
                    Official court-ready document with all findings and analysis
                </p>
            </div>
            {% endif %}
            
            <div class="forensic-note">
                <strong>🔒 Read-Only Disclaimer:</strong> This interface provides read-only access to forensic evidence. No modifications can be made to the original evidence or analysis results through this system.
            </div>
        </div>
    </div>
</body>
</html>
"""

@app.route('/')
def dashboard():
    """Main dashboard route - investigation overview with integration status"""
    # Get integration status
    integration_status = get_integration_status()
    
    # Load normalized case metadata
    case_metadata = load_case_metadata()
    
    # Get active case and available cases
    active_case = get_active_case()
    available_cases = AVAILABLE_CASES
    
    # Load case suspicion classification
    case_suspicion = load_case_suspicion(active_case)
    
    # Get pipeline status
    pipeline_status = get_pipeline_status()
    
    # Load available data gracefully
    timeline_data = load_timeline_data()
    analysis_data = load_analysis_data()
    hash_data = load_hash_data()
    report_data = load_report_data()
    
    # Prepare dashboard context
    context = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "integration_status": integration_status,
        "case_metadata": case_metadata,
        "active_case": active_case,
        "available_cases": available_cases,
        "case_suspicion": case_suspicion,
        "pipeline_status": pipeline_status,
        "timeline_events": len(timeline_data),
        "analysis_complete": all(
            isinstance(analysis_data.get(key, []), list) and len(analysis_data.get(key, [])) > 0
            for key in ["suspicious_behaviour", "malware_indicators", "timestamp_anomalies"]
        ),
        "hash_verified": hash_data.get("status") != "missing",
        "report_ready": report_data.get("status") != "missing"
    }
    
    return render_template_string(DASHBOARD_TEMPLATE, **context)

@app.route('/select_case', methods=['POST'])
def select_case():
    """Handle case selection"""
    case_id = request.form.get('case_id')
    
    # Validate case exists
    valid_case_ids = [case['case_id'] for case in AVAILABLE_CASES]
    if case_id in valid_case_ids:
        set_active_case(case_id)
        print(f"Active case set to: {case_id}")
    else:
        print(f"Invalid case ID: {case_id}")
    
    return redirect(url_for('dashboard'))

@app.route('/dashboard')
def dashboard_alt():
    """Alternative dashboard route"""
    return dashboard()

@app.route('/evidence')
def evidence():
    """Evidence integrity and hash verification route with graceful loading"""
    # Load normalized case metadata
    case_metadata = load_case_metadata()
    
    # Get evidence information
    evidence_info = get_evidence_info()
    
    # Load hash data for compatibility
    hash_data = load_hash_data()
    
    # Calculate total evidence files and readiness
    total_evidence_files = 0
    if evidence_info['raw_evidence']['available']:
        total_evidence_files += evidence_info['raw_evidence']['file_count']
    
    processed_counts = [evidence_info['processed_evidence'][key]['count'] 
                      for key in ['sms', 'calls', 'media', 'apps'] 
                      if evidence_info['processed_evidence'][key]['available']]
    total_evidence_files += sum(processed_counts)
    
    # Determine forensic readiness
    forensic_readiness = "Complete"
    if not evidence_info['hash_verification']['available']:
        forensic_readiness = "Partial"
    if not evidence_info['raw_evidence']['available'] and sum(processed_counts) == 0:
        forensic_readiness = "Incomplete"
    
    # Prepare evidence context
    context = {
        "case_metadata": case_metadata,
        "evidence_info": evidence_info,
        "total_evidence_files": total_evidence_files,
        "forensic_readiness": forensic_readiness,
        "hash_status": hash_data.get("status", "unknown"),
        "hash_message": hash_data.get("message", ""),
        "total_files": hash_data.get("total_files", 0) if hash_data.get("status") != "missing" else 0,
        "integrity_score": hash_data.get("integrity_score", 100) if hash_data.get("status") != "missing" else 0,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(EVIDENCE_TEMPLATE, **context)

@app.route('/timeline')
def timeline():
    """Unified timeline viewer route with graceful loading"""
    # Load timeline data gracefully
    timeline_data = load_timeline_data()
    
    # Calculate timeline statistics
    total_events = len(timeline_data)
    sources = list(set(event.get("source", "Unknown") for event in timeline_data)) if timeline_data else []
    
    # Count timestamp anomalies from analysis data
    anomaly_count = 0
    try:
        analysis_data = load_analysis_data()
        if 'timestamp_anomalies' in analysis_data and isinstance(analysis_data['timestamp_anomalies'], list):
            anomaly_count = len(analysis_data['timestamp_anomalies'])
    except:
        anomaly_count = 0
    
    # Prepare timeline context
    context = {
        "timeline_status": "loaded" if timeline_data else "missing",
        "total_events": total_events,
        "date_range_start": timeline_data[0].get("timestamp") if timeline_data else "Not available",
        "date_range_end": timeline_data[-1].get("timestamp") if timeline_data else "Not available",
        "sources": sources,
        "anomaly_count": anomaly_count,
        "events": timeline_data,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(TIMELINE_TEMPLATE, **context)

@app.route('/report')
def report():
    """Complete forensic report viewer route with graceful loading"""
    # Load report data gracefully
    report_data = load_report_data()
    
    # Get evidence information for counts
    evidence_info = get_evidence_info()
    
    # Calculate evidence counts
    evidence_counts = {
        'calls': evidence_info['processed_evidence']['calls']['count'] if evidence_info['processed_evidence']['calls']['available'] else 0,
        'messages': evidence_info['processed_evidence']['sms']['count'] if evidence_info['processed_evidence']['sms']['available'] else 0,
        'media': evidence_info['processed_evidence']['media']['count'] if evidence_info['processed_evidence']['media']['available'] else 0,
        'apps': evidence_info['processed_evidence']['apps']['count'] if evidence_info['processed_evidence']['apps']['available'] else 0
    }
    
    # Get timeline data for events analyzed
    timeline_data = load_timeline_data()
    events_analyzed = len(timeline_data)
    
    # Prepare report context
    context = {
        "report_status": report_data.get("status", "unknown"),
        "report_message": report_data.get("message", ""),
        "risk_level": report_data.get("risk_level", "Not assessed"),
        "total_events": events_analyzed,
        "report_timestamp": report_data.get("generation_timestamp", "Not available"),
        "evidence_counts": evidence_counts,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    return render_template_string(REPORT_TEMPLATE, **context)

@app.route('/download/report')
def download_report():
    """Safe download route for forensic PDF report (read-only)"""
    from flask import send_file
    
    # Try PDF first
    case_base_path = get_case_base_path()
    pdf_path = f"{case_base_path}/reports/forensic_report.pdf"
    
    if os.path.exists(pdf_path):
        try:
            active_case = get_active_case()
            return send_file(
                pdf_path,
                as_attachment=True,
                download_name=f"{active_case}_forensic_report.pdf",
                mimetype='application/pdf'
            )
        except Exception as e:
            print(f"Error serving PDF file: {e}")
            return "Error downloading PDF report", 500
    
    # Fallback to JSON if PDF not available
    json_path = f"{case_base_path}/reports/forensic_report.json"
    
    if not os.path.exists(json_path):
        return "Report not found", 404
    
    try:
        active_case = get_active_case()
        return send_file(
            json_path,
            as_attachment=True,
            download_name=f"{active_case}_forensic_report.json",
            mimetype='application/json'
        )
    except Exception as e:
        print(f"Error serving JSON file: {e}")
        return "Error downloading report", 500

@app.route('/api/status')
def api_status():
    """API endpoint for investigation status (read-only) with real integration checking"""
    # Get actual integration status
    integration_status = get_integration_status()
    
    # Load data to check actual status
    timeline_data = load_timeline_data()
    analysis_data = load_analysis_data()
    hash_data = load_hash_data()
    report_data = load_report_data()
    
    status = {
        "tool_version": "mobile-forensics-tool v1.0",
        "status": "ACTIVE",
        "timestamp": datetime.now().isoformat(),
        "integration": integration_status,
        "evidence_loaded": len(timeline_data) > 0,
        "analysis_complete": all(
            isinstance(analysis_data.get(key, []), list) and len(analysis_data.get(key, [])) > 0
            for key in ["suspicious_behaviour", "malware_indicators", "timestamp_anomalies"]
        ),
        "hash_verified": hash_data.get("status") not in ["missing", "error"],
        "report_generated": report_data.get("status") not in ["missing", "error"],
        "timeline_events": len(timeline_data),
        "completion_percentage": integration_status.get("completion_percentage", 0)
    }
    return jsonify(status)

# Robust file loading functions with graceful error handling
def load_timeline_data():
    """
    Load timeline data for display (read-only).
    
    INTEGRATOR NOTE: Run timeline/timeline_builder.py first to generate timeline.json
    
    Returns:
        - List of timeline events if file exists and is valid
        - Empty list with error logged if file missing or invalid
    """
    case_base_path = get_case_base_path()
    timeline_path = f"{case_base_path}/timeline/timeline.json"
    active_case = get_active_case()
    if not os.path.exists(timeline_path):
        print(f"Timeline not found for case {active_case}: Run timeline/timeline_builder.py first")
        return []
    
    try:
        with open(timeline_path, 'r') as f:
            data = json.load(f)
            # Validate it's a list
            if isinstance(data, list):
                print(f"Loaded {len(data)} timeline events")
                return data
            else:
                print("Invalid timeline format: Expected list of events")
                return []
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in timeline.json: {e}")
        return []
    except Exception as e:
        print(f"Error loading timeline: {e}")
        return []

def load_analysis_data():
    """
    Load analysis results for display (read-only).
    
    INTEGRATOR NOTE: Run analysis scripts first to generate findings.json
    - analysis/behaviour_analysis.py
    - analysis/malware_analysis.py  
    - analysis/anomaly_analysis.py
    - All merged into analysis/findings.json
    
    Returns:
        - Dictionary with merged analysis findings if file exists
        - Empty dictionary with status info if file missing
    """
    case_base_path = get_case_base_path()
    findings_path = f"{case_base_path}/analysis/findings.json"
    active_case = get_active_case()
    
    if not os.path.exists(findings_path):
        print(f"Merged findings not found for case {active_case}: Run analysis scripts to generate findings.json")
        return {
            "suspicious_behaviour": {"status": "missing", "message": "Analysis not completed yet"},
            "malware_indicators": {"status": "missing", "message": "Analysis not completed yet"},
            "timestamp_anomalies": {"status": "missing", "message": "Analysis not completed yet"}
        }
    
    try:
        with open(findings_path, 'r') as f:
            data = json.load(f)
            print("Loaded merged analysis findings")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in findings.json: {e}")
        return {
            "suspicious_behaviour": {"status": "error", "message": "Invalid JSON format"},
            "malware_indicators": {"status": "error", "message": "Invalid JSON format"},
            "timestamp_anomalies": {"status": "error", "message": "Invalid JSON format"}
        }
    except Exception as e:
        print(f"Error loading findings.json: {e}")
        return {
            "suspicious_behaviour": {"status": "error", "message": f"Load error: {str(e)}"},
            "malware_indicators": {"status": "error", "message": f"Load error: {str(e)}"},
            "timestamp_anomalies": {"status": "error", "message": f"Load error: {str(e)}"}
        }

def load_hash_data():
    """
    Load hash manifest for evidence integrity display (read-only).
    
    INTEGRATOR NOTE: Run analysis/hash_generator.py first to generate hashes.json
    
    Returns:
        - Hash manifest data if file exists
        - Status info if file missing
    """
    case_base_path = get_case_base_path()
    hash_path = f"{case_base_path}/evidence/hashes/hashes.json"
    active_case = get_active_case()
    if not os.path.exists(hash_path):
        print(f"Hash manifest not found for case {active_case}: Run analysis/hash_generator.py first")
        return {"status": "missing", "message": "Integrity verification pending"}
    
    try:
        with open(hash_path, 'r') as f:
            data = json.load(f)
            print(f"Loaded hash manifest with {data.get('total_files', 0)} files")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in hashes.json: {e}")
        return {"status": "error", "message": "Invalid JSON format"}
    except Exception as e:
        print(f"Error loading hash manifest: {e}")
        return {"status": "error", "message": f"Load error: {str(e)}"}

def load_report_data():
    """
    Load forensic report for display (read-only).
    
    INTEGRATOR NOTE: Run reports/generate_report.py first to generate forensic_report.json
    
    Returns:
        - Report data if file exists
        - Status info if file missing
    """
    case_base_path = get_case_base_path()
    report_path = f"{case_base_path}/reports/forensic_report.json"
    active_case = get_active_case()
    if not os.path.exists(report_path):
        print(f"Forensic report not found for case {active_case}: Run reports/generate_report.py first")
        return {"status": "missing", "message": "Report not generated yet"}
    
    try:
        with open(report_path, 'r') as f:
            data = json.load(f)
            print("Loaded forensic report")
            return data
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in forensic_report.json: {e}")
        return {"status": "error", "message": "Invalid JSON format"}
    except Exception as e:
        print(f"Error loading forensic report: {e}")
        return {"status": "error", "message": f"Load error: {str(e)}"}

def get_integration_status():
    """
    Check integration status by verifying which required files exist.
    
    Returns:
        - Dictionary with status of each integration component
    """
    case_base_path = get_case_base_path()
    status = {
        "timeline": os.path.exists(f"{case_base_path}/timeline/timeline.json"),
        "findings": os.path.exists(f"{case_base_path}/analysis/findings.json"),
        "hashes": os.path.exists(f"{case_base_path}/evidence/hashes/hashes.json"),
        "forensic_report": os.path.exists(f"{case_base_path}/reports/forensic_report.json")
    }
    
    # Calculate overall completion percentage
    completed = sum(status.values())
    total = len(status)
    status["completion_percentage"] = (completed / total) * 100
    status["overall_status"] = "Ready" if completed == total else f"In Progress ({completed}/{4})"
    
    return status

def classify_case_suspicion(case_id):
    """
    Implement rule-based suspicion classification for a case.
    
    Rules (deterministic, explainable):
    - suspicious_behaviour list not empty -> +1
    - timestamp_anomalies list not empty -> +1
    - malware_indicators list not empty -> +2
    - Activity between midnight and 4 AM detected in timeline -> +1
    
    Classification:
    - 0 points -> Clean
    - 1-2 points -> Suspicious
    - 3+ points -> Highly Suspicious
    
    Args:
        case_id: Case identifier
        
    Returns:
        dict: Suspicion classification with reasons
    """
    case_base_path = f"../cases/{case_id}"
    
    # Load analysis findings
    findings_path = f"{case_base_path}/analysis/findings.json"
    findings = {}
    reasons = []
    score = 0
    
    if os.path.exists(findings_path):
        try:
            with open(findings_path, 'r') as f:
                findings = json.load(f)
        except Exception as e:
            print(f"Error loading findings for case {case_id}: {e}")
    
    # Rule 1: suspicious_behaviour not empty → +1
    suspicious_behaviour = findings.get("suspicious_behaviour", [])
    if suspicious_behaviour and len(suspicious_behaviour) > 0:
        score += 1
        reasons.append(f"Suspicious behaviour indicators present ({len(suspicious_behaviour)} patterns)")
    
    # Rule 2: timestamp_anomalies not empty → +1
    timestamp_anomalies = findings.get("timestamp_anomalies", [])
    if timestamp_anomalies and len(timestamp_anomalies) > 0:
        score += 1
        reasons.append(f"Timestamp anomalies detected ({len(timestamp_anomalies)} anomalies)")
    
    # Rule 3: malware_indicators not empty → +2
    malware_indicators = findings.get("malware_indicators", [])
    if malware_indicators and len(malware_indicators) > 0:
        score += 2
        reasons.append(f"Malware indicators present ({len(malware_indicators)} indicators)")
    
    # Rule 4: Late-night activity (00:00–04:00) → +1
    timeline_path = f"{case_base_path}/timeline/timeline.json"
    late_night_activity = False
    
    if os.path.exists(timeline_path):
        try:
            with open(timeline_path, 'r') as f:
                timeline = json.load(f)
                
            for event in timeline:
                timestamp = event.get("timestamp", "")
                if timestamp:
                    try:
                        # Extract hour from timestamp
                        hour = int(timestamp.split(" ")[1].split(":")[0])
                        if 0 <= hour <= 3:  # 00:00-03:59
                            late_night_activity = True
                            break
                    except (ValueError, IndexError):
                        continue
                        
            if late_night_activity:
                score += 1
                reasons.append("Late-night activity detected (00:00-04:00)")
                
        except Exception as e:
            print(f"Error loading timeline for case {case_id}: {e}")
    
    # Classification
    if score == 0:
        suspicion_level = "Clean"
    elif score <= 2:
        suspicion_level = "Suspicious"
    else:
        suspicion_level = "Highly Suspicious"
    
    classification = {
        "suspicion_level": suspicion_level,
        "score": score,
        "reasons": reasons,
        "classification_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    # Save classification to case_status.json
    status_path = f"{case_base_path}/analysis/case_status.json"
    try:
        os.makedirs(os.path.dirname(status_path), exist_ok=True)
        with open(status_path, 'w') as f:
            json.dump(classification, f, indent=2)
        print(f"Saved suspicion classification for case {case_id}: {suspicion_level} (score: {score})")
    except Exception as e:
        print(f"Error saving case status for {case_id}: {e}")
    
    return classification

def load_case_suspicion(case_id):
    """
    Load existing suspicion classification or generate new one.
    
    Args:
        case_id: Case identifier
        
    Returns:
        dict: Suspicion classification
    """
    status_path = f"../cases/{case_id}/analysis/case_status.json"
    
    if os.path.exists(status_path):
        try:
            with open(status_path, 'r') as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading case status for {case_id}: {e}")
    
    # Generate new classification if not exists
    return classify_case_suspicion(case_id)

def normalize_case_metadata(metadata):
    """
    Normalize case metadata from different schema formats (CFReDS vs Live cases)
    
    Args:
        metadata (dict): Raw metadata from metadata.json
        
    Returns:
        dict: Normalized metadata with consistent field names
    """
    normalized = {}
    
    # Handle CFReDS case format
    if 'data_source' in metadata and 'CFReDS' in metadata.get('data_source', ''):
        normalized = {
            'case_id': metadata.get('case_id', 'Unknown'),
            'case_name': metadata.get('case_name', 'Unknown'),
            'investigator': metadata.get('investigator', 'Unknown'),
            'dataset_source': metadata.get('data_source', 'Unknown'),
            'device_type': metadata.get('device_type', 'Unknown'),
            'acquisition_method': 'CFReDS Reference Dataset',
            'case_status': metadata.get('case_status', 'Unknown'),
            'created_at': metadata.get('created_at', 'Unknown')
        }
    
    # Handle Live case format
    elif 'dataset_source' in metadata and 'Live Android' in metadata.get('dataset_source', ''):
        normalized = {
            'case_id': metadata.get('case_id', 'Unknown'),
            'case_name': f"Live Investigation - {metadata.get('device_model', 'Unknown Device')}",
            'investigator': metadata.get('investigator', 'Unknown'),
            'dataset_source': metadata.get('dataset_source', 'Unknown'),
            'device_type': metadata.get('device_model', 'Unknown'),
            'acquisition_method': metadata.get('acquisition_method', 'Live Android ADB Logical Acquisition'),
            'case_status': 'Active',
            'created_at': metadata.get('case_created', 'Unknown')
        }
    
    # Default fallback
    else:
        normalized = {
            'case_id': metadata.get('case_id', 'Unknown'),
            'case_name': metadata.get('case_name', 'Unknown Case'),
            'investigator': metadata.get('investigator', 'Unknown'),
            'dataset_source': metadata.get('data_source', metadata.get('dataset_source', 'Unknown')),
            'device_type': metadata.get('device_type', metadata.get('device_model', 'Unknown')),
            'acquisition_method': 'Unknown',
            'case_status': metadata.get('case_status', 'Unknown'),
            'created_at': metadata.get('created_at', metadata.get('case_created', 'Unknown'))
        }
    
    return normalized

def get_evidence_info():
    """
    Get evidence information for the active case
    
    Returns:
        dict: Evidence counts and availability
    """
    case_base_path = get_case_base_path()
    active_case = get_active_case()
    
    evidence_info = {
        'raw_evidence': {
            'available': False,
            'file_count': 0,
            'total_size_mb': 0,
            'message': 'Raw evidence not available for this case'
        },
        'hash_verification': {
            'available': False,
            'algorithm': 'SHA-256',
            'files_hashed': 0,
            'status': 'Not Generated',
            'message': 'Hash verification not yet generated for this case'
        },
        'processed_evidence': {
            'sms': {'available': False, 'count': 0},
            'calls': {'available': False, 'count': 0},
            'media': {'available': False, 'count': 0},
            'apps': {'available': False, 'count': 0}
        }
    }
    
    # Check raw evidence
    raw_path = f"{case_base_path}/evidence/raw"
    if os.path.exists(raw_path):
        try:
            raw_files = []
            total_size = 0
            for root, dirs, files in os.walk(raw_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    if os.path.isfile(file_path):
                        raw_files.append(file)
                        total_size += os.path.getsize(file_path)
            
            if raw_files:
                evidence_info['raw_evidence'] = {
                    'available': True,
                    'file_count': len(raw_files),
                    'total_size_mb': round(total_size / (1024 * 1024), 2),
                    'message': f'{len(raw_files)} raw evidence files ({round(total_size / (1024 * 1024), 2)} MB)'
                }
        except Exception as e:
            print(f"Error scanning raw evidence: {e}")
    
    # Check hash verification
    hash_path = f"{case_base_path}/evidence/hashes/hashes.json"
    if os.path.exists(hash_path):
        try:
            with open(hash_path, 'r') as f:
                hash_data = json.load(f)
                evidence_info['hash_verification'] = {
                    'available': True,
                    'algorithm': 'SHA-256',
                    'files_hashed': hash_data.get('total_files', 0),
                    'status': 'VERIFIED',
                    'message': f'{hash_data.get("total_files", 0)} files verified with SHA-256'
                }
        except Exception as e:
            print(f"Error loading hash data: {e}")
    
    # Check processed evidence
    processed_path = f"{case_base_path}/evidence/processed"
    if os.path.exists(processed_path):
        evidence_types = ['sms.json', 'calls.json', 'media.json', 'apps.json']
        for evidence_type in evidence_types:
            type_path = os.path.join(processed_path, evidence_type)
            if os.path.exists(type_path):
                try:
                    with open(type_path, 'r') as f:
                        data = json.load(f)
                        count = len(data) if isinstance(data, list) else 0
                        key = evidence_type.replace('.json', '')
                        evidence_info['processed_evidence'][key] = {
                            'available': True,
                            'count': count
                        }
                except Exception as e:
                    print(f"Error loading {evidence_type}: {e}")
    
    print(f"Evidence info for {active_case}: {evidence_info}")
    return evidence_info

def get_pipeline_status():
    """
    Get pipeline status for the active case
    
    Returns:
        dict: Status of each pipeline component
    """
    case_base_path = get_case_base_path()
    active_case = get_active_case()
    
    # Check each pipeline component
    status = {
        'raw_evidence': False,
        'hash_manifest': False,
        'analysis_completed': False,
        'timeline_generated': False,
        'pdf_report_available': False
    }
    
    # Check raw evidence
    raw_path = f"{case_base_path}/evidence/raw"
    if os.path.exists(raw_path):
        try:
            raw_files = os.listdir(raw_path)
            status['raw_evidence'] = len(raw_files) > 0
        except:
            status['raw_evidence'] = False
    
    # Check hash manifest
    hash_path = f"{case_base_path}/evidence/hashes/hashes.json"
    status['hash_manifest'] = os.path.exists(hash_path)
    
    # Check analysis
    analysis_path = f"{case_base_path}/analysis/findings.json"
    status['analysis_completed'] = os.path.exists(analysis_path)
    
    # Check timeline
    timeline_path = f"{case_base_path}/timeline/timeline.json"
    status['timeline_generated'] = os.path.exists(timeline_path)
    
    # Check PDF report
    report_path = f"{case_base_path}/reports/forensic_report.pdf"
    status['pdf_report_available'] = os.path.exists(report_path)
    
    print(f"Pipeline status for {active_case}: {status}")
    return status

def load_case_metadata():
    """
    Load case metadata for dashboard display (read-only).
    
    Returns:
        - Case metadata dictionary if file exists
        - Default metadata if file missing
    """
    case_base_path = get_case_base_path()
    metadata_path = f"{case_base_path}/metadata.json"
    active_case = get_active_case()
    
    if not os.path.exists(metadata_path):
        print(f"Case metadata not found for case {active_case}")
        return {
            "case_id": "UNKNOWN",
            "case_name": "Unknown Case",
            "investigator": "Unknown Investigator",
            "data_source": "Unknown Source",
            "device_type": "Unknown Device",
            "case_status": "Unknown"
        }
    
    try:
        with open(metadata_path, 'r') as f:
            data = json.load(f)
            # Normalize metadata for consistent display
            normalized = normalize_case_metadata(data)
            print(f"Loaded case metadata for {normalized.get('case_id', 'UNKNOWN')}")
            return normalized
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in metadata.json: {e}")
        return {
            "case_id": "ERROR",
            "case_name": "Error Loading Case",
            "investigator": "Error",
            "data_source": "Error",
            "device_type": "Error",
            "case_status": "Error"
        }
    except Exception as e:
        print(f"Error loading case metadata: {e}")
        return {
            "case_id": "ERROR",
            "case_name": "Error Loading Case",
            "investigator": "Error",
            "data_source": "Error",
            "device_type": "Error",
            "case_status": "Error"
        }

if __name__ == '__main__':
    print("Starting Mobile Forensics Tool - Secure Read-Only Web Viewer")
    print("SECURITY NOTICE: This is a READ-ONLY interface for forensic evidence viewing")
    print("No evidence modification is possible through this interface")
    print("Access: http://localhost:5000")
    
    # Run Flask app in debug mode for development
    app.run(debug=True, host='0.0.0.0', port=5000)
